import { MODULES_ROUTES } from "./modules.routes";

export const PEDAGOGICAL_INNOVATION_PAGES = {
  PRESENTATION: 'presentacion',
  PHILOSOPHICAL_SESSIONS: 'sesiones-filosoficas',
  REFLECTIVE_STRATEGIES: 'estrategias-reflexivas',
  PHILOSOPHICAL_WORKSHOPS: 'talleres-filosoficas',
  CURRENT_PHILOSOPHICAL: 'actualidad-filosoficas'
} as const;

export const PEDAGOGICAL_INNOVATION_ROUTES = {
  PRESENTATION: `${MODULES_ROUTES.PEDAGOGICAL_INNOVATION}/${PEDAGOGICAL_INNOVATION_PAGES.PRESENTATION}`,
  PHILOSOPHICAL_SESSIONS: `${MODULES_ROUTES.PEDAGOGICAL_INNOVATION}/${PEDAGOGICAL_INNOVATION_PAGES.PHILOSOPHICAL_SESSIONS}`,
  REFLECTIVE_STRATEGIES: `${MODULES_ROUTES.PEDAGOGICAL_INNOVATION}/${PEDAGOGICAL_INNOVATION_PAGES.REFLECTIVE_STRATEGIES}`,
  PHILOSOPHICAL_WORKSHOPS: `${MODULES_ROUTES.PEDAGOGICAL_INNOVATION}/${PEDAGOGICAL_INNOVATION_PAGES.PHILOSOPHICAL_WORKSHOPS}`,
  CURRENT_PHILOSOPHICAL: `${MODULES_ROUTES.PEDAGOGICAL_INNOVATION}/${PEDAGOGICAL_INNOVATION_PAGES.CURRENT_PHILOSOPHICAL}`
} as const;

export const REFLECTIVE_STRATEGIES_PAGES = {
  PHILOSOPHICAL_STRATEGIES: 'estrategias-filosoficas',
  PROCESSED_PRODUCTS: 'productos-elaborados'
} as const;

export const REFLECTIVE_STRATEGIES_ROUTES = {
  PHILOSOPHICAL_STRATEGIES: `${PEDAGOGICAL_INNOVATION_ROUTES.REFLECTIVE_STRATEGIES}/${REFLECTIVE_STRATEGIES_PAGES.PHILOSOPHICAL_STRATEGIES}`,
  PROCESSED_PRODUCTS: `${PEDAGOGICAL_INNOVATION_ROUTES.REFLECTIVE_STRATEGIES}/${REFLECTIVE_STRATEGIES_PAGES.PROCESSED_PRODUCTS}`
} as const;
